---
spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:development}
  mail:
    default-encoding: UTF-8
    host: smtp.mail.ru
    username: muzalev_as@mail.ru
    password: 18LNePAB03pfqvKjL2jw
    port: 465
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            required: true
            enable: true
    protocol: smtps
    test-connection: false
  jpa:
    show-sql: true
    properties:
      connection:
        characterEncoding: utf-8
        Charset: utf-8
        useUnicode: true
    hibernate:
      ddl-auto: update
  output:
    ansi:
      enabled: always
  freemarker:
    expose-request-attributes: true

mail:
  debug: true

sentry:
  dsn: https://b96d7a9cc4dd6afe61ffd4ffd9f8dcea@o4506914214248448.ingest.us.sentry.io/4506914217590784
  # Set traces-sample-rate to 1.0 to capture 100% of transactions for performance monitoring.
  # We recommend adjusting this value in production.
  traces-sample-rate: 1.0

